[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
TF_CPP_MIN_LOG_LEVEL = "2"
TF_ENABLE_ONEDNN_OPTS = "0"
